name: Build and Deploy Prod Site

on:
  create:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
          VITE_APIKEY: ${{ secrets.FIREBASE_WEB_API_KEY_PROD }}
          VITE_AUTHDOMAIN: "coreofscience.firebaseapp.com"
          VITE_DATABASEURL: "https://coreofscience.firebaseio.com"
          VITE_PROJECTID: "coreofscience"
          VITE_STORAGEBUCKET: "coreofscience.appspot.com"
          VITE_MESSAGINGSENDERID: "217902041600"
          VITE_APPID: "1:217902041600:web:54618397fad21282b426e5"
          VITE_MEASUREMENTID: "G-9SHWB33EEK"

      - name: Deploy
        run: |
          npm install -g firebase-tools
          firebase deploy -- --token=${{ secrets.FIREBASE_TOKEN }} -P prod
