name: Deploy to Preview Channel

on:
  pull_request:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: |
          npm ci
          npm run build
        env:
          CI: true
          REACT_APP_APIKEY: ${{ secrets.FIREBASE_WEB_API_KEY_DEV }}
          REACT_APP_AUTHDOMAIN: "coreofscience-dev.firebaseapp.com"
          REACT_APP_DATABASEURL: "https://coreofscience-dev.firebaseio.com"
          REACT_APP_PROJECTID: "coreofscience-dev"
          REACT_APP_STORAGEBUCKET: "coreofscience-dev.appspot.com"
          REACT_APP_MESSAGINGSENDERID: "421154467745"
          REACT_APP_APPID: "1:421154467745:web:d7dd5ed17243869ba765e0"
          REACT_APP_MEASUREMENTID: "G-N2245DYRQN"

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
