name: Build and Deploy Dev Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Use latest python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
          VITE_APIKEY: ${{ secrets.FIREBASE_WEB_API_KEY_DEV }}
          VITE_AUTHDOMAIN: "coreofscience-dev.firebaseapp.com"
          VITE_DATABASEURL: "https://coreofscience-dev.firebaseio.com"
          VITE_PROJECTID: "coreofscience-dev"
          VITE_STORAGEBUCKET: "coreofscience-dev.appspot.com"
          VITE_MESSAGINGSENDERID: "421154467745"
          VITE_APPID: "1:421154467745:web:d7dd5ed17243869ba765e0"
          VITE_MEASUREMENTID: "G-N2245DYRQN"

      - name: Deploy
        run: |
          echo $SERVICE_ACCOUNT > .credentials.json
          npm run deploy -- -P dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: .credentials.json
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_DEV_SERVICE_ACCOUNT }}
